require File.join(File.dirname(__FILE__), "spec_helper.rb")
require 'rubygems'
require 'rake'
require 'spec/rake/spectask'

basedir = File.dirname(__FILE__)

desc "Run all specs"
Spec::Rake::SpecTask.new('all') do |t|
    t.spec_files = FileList['unit/facter/*.rb']
    t.spec_opts = ['--options', 'spec.opts']
end

task :default => [:all]
